import type { CellRecord } from './types'

export const DEMO_CELLS: CellRecord[] = [
  {
    id: 'LFP-100Ah-PR-01',
    model: 'TS-LFP100P (Prismatic)',
    chemistry: 'LFP',
    formFactor: 'prismatic',
    capacityAh: 100,
    nominalV: 3.2,
    vMin: 2.5,
    vMax: 3.65,
    maxDischargeCCont: 2,
    maxDischargeCPulse: 4,
    maxChargeCCont: 1,
    tempDischargeMinC: -20,
    tempDischargeMaxC: 55,
    tempChargeMinC: 0,
    tempChargeMaxC: 45,
    massG: 1950,
    resistanceMOhm25C: 0.35,
    cycleLife80DoD25C: 4000,
    costTier: 2,
    dataQuality: 'demo',
    sourceNote: 'Demo placeholder values for concept UI.',
  },
  {
    id: 'LFP-280Ah-PR-01',
    model: 'TS-LFP280P (Prismatic)',
    chemistry: 'LFP',
    formFactor: 'prismatic',
    capacityAh: 280,
    nominalV: 3.2,
    vMin: 2.5,
    vMax: 3.65,
    maxDischargeCCont: 1,
    maxDischargeCPulse: 2,
    maxChargeCCont: 0.5,
    tempDischargeMinC: -20,
    tempDischargeMaxC: 55,
    tempChargeMinC: 0,
    tempChargeMaxC: 45,
    massG: 5400,
    resistanceMOhm25C: 0.18,
    cycleLife80DoD25C: 6000,
    costTier: 1,
    dataQuality: 'demo',
  },
  {
    id: 'NMC-50Ah-Pouch-01',
    model: 'TS-NMC50 (Pouch)',
    chemistry: 'NMC',
    formFactor: 'pouch',
    capacityAh: 50,
    nominalV: 3.65,
    vMin: 2.8,
    vMax: 4.2,
    maxDischargeCCont: 3,
    maxDischargeCPulse: 6,
    maxChargeCCont: 1.5,
    tempDischargeMinC: -20,
    tempDischargeMaxC: 55,
    tempChargeMinC: 0,
    tempChargeMaxC: 45,
    massG: 820,
    resistanceMOhm25C: 0.6,
    cycleLife80DoD25C: 1800,
    costTier: 3,
    dataQuality: 'demo',
  },
  {
    id: 'NMC-72Ah-Pouch-01',
    model: 'TS-NMC72 (Pouch)',
    chemistry: 'NMC',
    formFactor: 'pouch',
    capacityAh: 72,
    nominalV: 3.65,
    vMin: 2.8,
    vMax: 4.2,
    maxDischargeCCont: 4,
    maxDischargeCPulse: 8,
    maxChargeCCont: 2,
    tempDischargeMinC: -20,
    tempDischargeMaxC: 55,
    tempChargeMinC: 0,
    tempChargeMaxC: 45,
    massG: 1100,
    resistanceMOhm25C: 0.5,
    cycleLife80DoD25C: 1600,
    costTier: 4,
    dataQuality: 'demo',
  },
  {
    id: 'NMC-5Ah-21700-HP-01',
    model: 'TS-NMC5-21700 HP',
    chemistry: 'NMC',
    formFactor: 'cylindrical',
    capacityAh: 5.0,
    nominalV: 3.6,
    vMin: 2.8,
    vMax: 4.2,
    maxDischargeCCont: 10,
    maxDischargeCPulse: 20,
    maxChargeCCont: 3,
    tempDischargeMinC: -20,
    tempDischargeMaxC: 60,
    tempChargeMinC: 0,
    tempChargeMaxC: 45,
    massG: 70,
    resistanceMOhm25C: 12,
    cycleLife80DoD25C: 800,
    costTier: 5,
    dataQuality: 'demo',
  },
  {
    id: 'NCA-5Ah-21700-01',
    model: 'TS-NCA5-21700',
    chemistry: 'NCA',
    formFactor: 'cylindrical',
    capacityAh: 5.0,
    nominalV: 3.6,
    vMin: 2.8,
    vMax: 4.2,
    maxDischargeCCont: 5,
    maxDischargeCPulse: 10,
    maxChargeCCont: 1.5,
    tempDischargeMinC: -20,
    tempDischargeMaxC: 60,
    tempChargeMinC: 0,
    tempChargeMaxC: 45,
    massG: 69,
    resistanceMOhm25C: 15,
    cycleLife80DoD25C: 1000,
    costTier: 4,
    dataQuality: 'demo',
  },
  {
    id: 'NMC-3Ah-18650-01',
    model: 'TS-NMC3-18650',
    chemistry: 'NMC',
    formFactor: 'cylindrical',
    capacityAh: 3.0,
    nominalV: 3.6,
    vMin: 2.8,
    vMax: 4.2,
    maxDischargeCCont: 5,
    maxDischargeCPulse: 10,
    maxChargeCCont: 1,
    tempDischargeMinC: -20,
    tempDischargeMaxC: 60,
    tempChargeMinC: 0,
    tempChargeMaxC: 45,
    massG: 45,
    resistanceMOhm25C: 28,
    cycleLife80DoD25C: 600,
    costTier: 3,
    dataQuality: 'demo',
  },
  {
    id: 'LTO-20Ah-Pouch-01',
    model: 'TS-LTO20 (Pouch)',
    chemistry: 'LTO',
    formFactor: 'pouch',
    capacityAh: 20,
    nominalV: 2.3,
    vMin: 1.6,
    vMax: 2.75,
    maxDischargeCCont: 10,
    maxDischargeCPulse: 20,
    maxChargeCCont: 5,
    tempDischargeMinC: -30,
    tempDischargeMaxC: 55,
    tempChargeMinC: -10,
    tempChargeMaxC: 45,
    massG: 520,
    resistanceMOhm25C: 0.9,
    cycleLife80DoD25C: 12000,
    costTier: 5,
    dataQuality: 'demo',
  },
  {
    id: 'LFP-20Ah-Pouch-01',
    model: 'TS-LFP20 (Pouch)',
    chemistry: 'LFP',
    formFactor: 'pouch',
    capacityAh: 20,
    nominalV: 3.2,
    vMin: 2.5,
    vMax: 3.65,
    maxDischargeCCont: 5,
    maxDischargeCPulse: 10,
    maxChargeCCont: 2,
    tempDischargeMinC: -20,
    tempDischargeMaxC: 55,
    tempChargeMinC: 0,
    tempChargeMaxC: 45,
    massG: 430,
    resistanceMOhm25C: 1.8,
    cycleLife80DoD25C: 3500,
    costTier: 3,
    dataQuality: 'demo',
  },
  {
    id: 'LFP-3.2Ah-32700-01',
    model: 'TS-LFP3.2-32700',
    chemistry: 'LFP',
    formFactor: 'cylindrical',
    capacityAh: 3.2,
    nominalV: 3.2,
    vMin: 2.5,
    vMax: 3.65,
    maxDischargeCCont: 8,
    maxDischargeCPulse: 15,
    maxChargeCCont: 2,
    tempDischargeMinC: -20,
    tempDischargeMaxC: 55,
    tempChargeMinC: 0,
    tempChargeMaxC: 45,
    massG: 63,
    resistanceMOhm25C: 22,
    cycleLife80DoD25C: 2500,
    costTier: 2,
    dataQuality: 'demo',
  },
  {
    id: 'LFP-50Ah-PR-01',
    model: 'TS-LFP50P (Prismatic)',
    chemistry: 'LFP',
    formFactor: 'prismatic',
    capacityAh: 50,
    nominalV: 3.2,
    vMin: 2.5,
    vMax: 3.65,
    maxDischargeCCont: 3,
    maxDischargeCPulse: 6,
    maxChargeCCont: 1,
    tempDischargeMinC: -20,
    tempDischargeMaxC: 55,
    tempChargeMinC: 0,
    tempChargeMaxC: 45,
    massG: 980,
    resistanceMOhm25C: 0.6,
    cycleLife80DoD25C: 3500,
    costTier: 2,
    dataQuality: 'demo',
  },
  {
    id: 'LFP-150Ah-PR-01',
    model: 'TS-LFP150P (Prismatic)',
    chemistry: 'LFP',
    formFactor: 'prismatic',
    capacityAh: 150,
    nominalV: 3.2,
    vMin: 2.5,
    vMax: 3.65,
    maxDischargeCCont: 1.5,
    maxDischargeCPulse: 3,
    maxChargeCCont: 0.8,
    tempDischargeMinC: -20,
    tempDischargeMaxC: 55,
    tempChargeMinC: 0,
    tempChargeMaxC: 45,
    massG: 2900,
    resistanceMOhm25C: 0.26,
    cycleLife80DoD25C: 5000,
    costTier: 1,
    dataQuality: 'demo',
  },
  {
    id: 'NMC-100Ah-PR-01',
    model: 'TS-NMC100P (Prismatic)',
    chemistry: 'NMC',
    formFactor: 'prismatic',
    capacityAh: 100,
    nominalV: 3.65,
    vMin: 2.8,
    vMax: 4.2,
    maxDischargeCCont: 2,
    maxDischargeCPulse: 4,
    maxChargeCCont: 1,
    tempDischargeMinC: -20,
    tempDischargeMaxC: 55,
    tempChargeMinC: 0,
    tempChargeMaxC: 45,
    massG: 1750,
    resistanceMOhm25C: 0.45,
    cycleLife80DoD25C: 1600,
    costTier: 4,
    dataQuality: 'demo',
  },
  {
    id: 'NMC-120Ah-PR-01',
    model: 'TS-NMC120P (Prismatic)',
    chemistry: 'NMC',
    formFactor: 'prismatic',
    capacityAh: 120,
    nominalV: 3.65,
    vMin: 2.8,
    vMax: 4.2,
    maxDischargeCCont: 2.5,
    maxDischargeCPulse: 5,
    maxChargeCCont: 1,
    tempDischargeMinC: -20,
    tempDischargeMaxC: 55,
    tempChargeMinC: 0,
    tempChargeMaxC: 45,
    massG: 2050,
    resistanceMOhm25C: 0.4,
    cycleLife80DoD25C: 1400,
    costTier: 5,
    dataQuality: 'demo',
  },
  {
    id: 'NMC-2.5Ah-18650-HP-01',
    model: 'TS-NMC2.5-18650 HP',
    chemistry: 'NMC',
    formFactor: 'cylindrical',
    capacityAh: 2.5,
    nominalV: 3.6,
    vMin: 2.8,
    vMax: 4.2,
    maxDischargeCCont: 15,
    maxDischargeCPulse: 25,
    maxChargeCCont: 3,
    tempDischargeMinC: -20,
    tempDischargeMaxC: 60,
    tempChargeMinC: 0,
    tempChargeMaxC: 45,
    massG: 44,
    resistanceMOhm25C: 18,
    cycleLife80DoD25C: 500,
    costTier: 5,
    dataQuality: 'demo',
  },
  {
    id: 'NCA-4.8Ah-4680-01',
    model: 'TS-NCA4.8-4680',
    chemistry: 'NCA',
    formFactor: 'cylindrical',
    capacityAh: 4.8,
    nominalV: 3.6,
    vMin: 2.8,
    vMax: 4.2,
    maxDischargeCCont: 7,
    maxDischargeCPulse: 12,
    maxChargeCCont: 1.5,
    tempDischargeMinC: -20,
    tempDischargeMaxC: 60,
    tempChargeMinC: 0,
    tempChargeMaxC: 45,
    massG: 280,
    resistanceMOhm25C: 4.5,
    cycleLife80DoD25C: 900,
    costTier: 4,
    dataQuality: 'demo',
  },
  {
    id: 'LTO-10Ah-32700-01',
    model: 'TS-LTO10-32700',
    chemistry: 'LTO',
    formFactor: 'cylindrical',
    capacityAh: 10,
    nominalV: 2.3,
    vMin: 1.6,
    vMax: 2.75,
    maxDischargeCCont: 15,
    maxDischargeCPulse: 25,
    maxChargeCCont: 8,
    tempDischargeMinC: -30,
    tempDischargeMaxC: 55,
    tempChargeMinC: -10,
    tempChargeMaxC: 45,
    massG: 240,
    resistanceMOhm25C: 3.2,
    cycleLife80DoD25C: 15000,
    costTier: 5,
    dataQuality: 'demo',
  },
  {
    id: 'NMC-12Ah-32700-01',
    model: 'TS-NMC12-32700',
    chemistry: 'NMC',
    formFactor: 'cylindrical',
    capacityAh: 12,
    nominalV: 3.6,
    vMin: 2.8,
    vMax: 4.2,
    maxDischargeCCont: 8,
    maxDischargeCPulse: 15,
    maxChargeCCont: 2,
    tempDischargeMinC: -20,
    tempDischargeMaxC: 60,
    tempChargeMinC: 0,
    tempChargeMaxC: 45,
    massG: 240,
    resistanceMOhm25C: 6.2,
    cycleLife80DoD25C: 700,
    costTier: 4,
    dataQuality: 'demo',
  },
  {
    id: 'LFP-8Ah-26650-01',
    model: 'TS-LFP8-26650',
    chemistry: 'LFP',
    formFactor: 'cylindrical',
    capacityAh: 8,
    nominalV: 3.2,
    vMin: 2.5,
    vMax: 3.65,
    maxDischargeCCont: 10,
    maxDischargeCPulse: 18,
    maxChargeCCont: 3,
    tempDischargeMinC: -20,
    tempDischargeMaxC: 55,
    tempChargeMinC: 0,
    tempChargeMaxC: 45,
    massG: 140,
    resistanceMOhm25C: 9,
    cycleLife80DoD25C: 2000,
    costTier: 3,
    dataQuality: 'demo',
  },
]

export function getDemoCellById(id: string): CellRecord | undefined {
  return DEMO_CELLS.find((c) => c.id === id)
}
